name: Amazon Linux 2

on: [push]

jobs:
  linux:
    name: Amazon Linux 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: .github/docker.sh SystemExtras 'swift test -Xswiftc -warnings-as-errors' 5.6.1 amazonlinux2
