name: Windows 2019

on: [push]

jobs:
  Windows:
    name: Windows
    runs-on: windows-2019
    env:
      SWIFT_RELEASE: 5.6.1-RELEASE
    steps:
    - name: Cache Swift Installation
      id: cache-swift-installation
      uses: actions/cache@v3
      with:
        path: C:\Library\Developer\Toolchains
        key: ${{ env.SWIFT_RELEASE }}
    - name: Install Swift
      if: steps.cache-swift-installation.outputs.cache-hit != 'true'
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-${{ env.SWIFT_RELEASE }}
        tag: ${{ env.SWIFT_RELEASE }}
    - name: Check out
      uses: actions/checkout@v2
    - name: Test
      shell: cmd
      run: |
        echo on
        C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift-test.exe
